### ISSUE TITLE
MissingRequiredParameter error on `npm run create`

### ISSUE THREAD

**Issue by TheLucasMoore** [arc-repos/arc-workflows#13]
When creating a simple hello world app (named `pizza` because, hey, that's a bit more interesting), I am running into an issue when deploying. 

I am not trying to create any tables, but the `npm run create` script seems to be trying to make Dynamo tables and failing on validation. 

Here's the error I see, for both staging and production tables.

```
create @tables pizza-production-arc-sessions
{ MissingRequiredParameter: Missing required key 'AttributeType' in params.AttributeDefinitions[1]
    at ParamValidator.fail (/Users/Lucas/Development/repos/aws_pizza/arc_pizza/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateStructure (/Users/Lucas/Development/repos/aws_pizza/arc_pizza/node_modules/aws-sdk/lib/param_validator.js:61:14)
    at ParamValidator.validateMember (/Users/Lucas/Development/repos/aws_pizza/arc_pizza/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validateList (/Users/Lucas/Development/repos/aws_pizza/arc_pizza/node_modules/aws-sdk/lib/param_validator.js:103:14)
    at ParamValidator.validateMember (/Users/Lucas/Development/repos/aws_pizza/arc_pizza/node_modules/aws-sdk/lib/param_validator.js:90:21)
    at ParamValidator.validateStructure (/Users/Lucas/Development/repos/aws_pizza/arc_pizza/node_modules/aws-sdk/lib/param_validator.js:75:14)
    at ParamValidator.validateMember (/Users/Lucas/Development/repos/aws_pizza/arc_pizza/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (/Users/Lucas/Development/repos/aws_pizza/arc_pizza/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/Users/Lucas/Development/repos/aws_pizza/arc_pizza/node_modules/aws-sdk/lib/event_listeners.js:125:42)
    at Request.callListeners (/Users/Lucas/Development/repos/aws_pizza/arc_pizza/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
  message: 'Missing required key \'AttributeType\' in params.AttributeDefinitions[1]',
  code: 'MissingRequiredParameter',
  time: 2017-08-13T04:32:54.301Z }
```

**Comment by brianleroux** [comment]
Try running `npm update @architect/workflows --save` (Or `--save-dev` if you put it there) and re-run the create---accidentally slipped a bug in yesterday but its fixed now (I hope!)

**Comment by TheLucasMoore** [comment]
Yeah that fixed it! Thanks Brian.
