### ISSUE TITLE
npx create throws Invalid Method Identifier specified error

### ISSUE THREAD

**Issue by asunar** [arc-repos/arc-workflows#136]
**Describe the bug**
Quickstart guide throws an error at npx create

**To Reproduce**
1. Follow the instructions on https://arc.codes/quickstart/install
2. See error

**Expected behavior**
No error

**Screenshots**
![image](https://user-images.githubusercontent.com/204049/44676161-11c66b80-a9f8-11e8-9bd7-daa6023ac626.png)

**Desktop (please complete the following information):**
 - OS: Win 10 using git bash( git version 2.17.1.windows.2)

**Comment by brianleroux** [comment]
Ok! weird, so the lambda part worked but looks like an error in API Gateay. What does your .arc file contain?

**Comment by asunar** [comment]
```
@app
testapp

@html
get /
```

**Comment by asunar** [comment]
Same result using window terminal (cmd)

**Comment by brianleroux** [comment]
hmmm, so the source of the error is here https://github.com/arc-repos/arc-workflows/blob/master/src/create/aws/_create-route/_create-resource/02-setup-request.js#L52

But I suspect that isn't the error at all. Can you see the RestAPI in AWS Console under API Gateway?

**Comment by brianleroux** [comment]
(also idk but it may be a race condition… it is safe to re-run `npx create` and see if it works)

**Comment by asunar** [comment]
Is this the RestAPI you're referring to?
![image](https://user-images.githubusercontent.com/204049/44677118-c6fa2300-a9fa-11e8-8614-2c2bb27f49c7.png)

**Comment by asunar** [comment]
```
$ cat .arc
@app
testapp

@html
get /

$ npx create

        ARC_APP_NAME testapp
          AWS_REGION us-west-1
         AWS_PROFILE personal

                Node 8.11.3
                 npm 6.1.0
                .arc 3.4.1

⡗ skip @html / exists
putIntegration failed NotFoundException { restApiId: 'kxia35w1j8', resourceId: 'xqvqvpvrp0' }
Error Invalid Method identifier specified
NotFoundException: Invalid Method identifier specified
    at Object.extractError (C:\code\mytestapp\node_modules\aws-sdk\lib\protocol\json.js:48:27)
    at Request.extractError (C:\code\mytestapp\node_modules\aws-sdk\lib\protocol\rest_json.js:52:8)
    at Request.callListeners (C:\code\mytestapp\node_modules\aws-sdk\lib\sequential_executor.js:105:20)
    at Request.emit (C:\code\mytestapp\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (C:\code\mytestapp\node_modules\aws-sdk\lib\request.js:683:14)
    at Request.transition (C:\code\mytestapp\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\code\mytestapp\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\code\mytestapp\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\code\mytestapp\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\code\mytestapp\node_modules\aws-sdk\lib\request.js:685:12)

$ npx create

        ARC_APP_NAME testapp
          AWS_REGION us-west-1
         AWS_PROFILE personal

                Node 8.11.3
                 npm 6.1.0
                .arc 3.4.1

⢼ skip @html / exists
putIntegration failed NotFoundException { restApiId: '3lli30r0jh', resourceId: 'odxjphh8n7' }
Error Invalid Method identifier specified
NotFoundException: Invalid Method identifier specified
    at Object.extractError (C:\code\mytestapp\node_modules\aws-sdk\lib\protocol\json.js:48:27)
    at Request.extractError (C:\code\mytestapp\node_modules\aws-sdk\lib\protocol\rest_json.js:52:8)
    at Request.callListeners (C:\code\mytestapp\node_modules\aws-sdk\lib\sequential_executor.js:105:20)
    at Request.emit (C:\code\mytestapp\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (C:\code\mytestapp\node_modules\aws-sdk\lib\request.js:683:14)
    at Request.transition (C:\code\mytestapp\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\code\mytestapp\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\code\mytestapp\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\code\mytestapp\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\code\mytestapp\node_modules\aws-sdk\lib\request.js:685:12)


```

**Comment by brianleroux** [comment]
np!!! awesome I love these sorts of issues ❤️
