### ISSUE TITLE
Sandbox errors when function res is invoked with status

### ISSUE THREAD

**Issue by ryanblock** [arc-repos/arc-workflows#156]
When a function is invoked with `status`, sandbox errors on request. Example:
```
res({
    status: 500,
    html: 'foo'
  })
```
Error:
```
/project/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

TypeError: Cannot read property 'status' of undefined
    at _res (/project/node_modules/@architect/workflows/src/sandbox/http/_response.js:48:21)
    at _write (/project/src/html/get-000page/node_modules/@architect/functions/src/http/_response.js:22:7)
    at _update (/project/src/html/get-000page/node_modules/@architect/functions/src/http/session/write.js:26:5)
    at Response._create (/project/src/html/get-000page/node_modules/@architect/functions/src/http/session/_update.js:16:7)
    at Request.<anonymous> (/project/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/project/node_modules/aws-sdk/lib/sequential_executor.js:109:20)
    at Request.emit (/project/node_modules/aws-sdk/lib/sequential_executor.js:81:10)
    at Request.emit (/project/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/project/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/project/node_modules/aws-sdk/lib/state_machine.js:14:12)
```
Error does not replicate with status not set, i.e.:
```
res({
    html: 'foo'
  })
```

**Comment by brianleroux** [comment]
sorry about that! should be fixed in `@architect/workflows@3.5.10`
