### ISSUE TITLE
add fully qualified url for 302 redirects

### ISSUE THREAD

**Issue by brianleroux** [arc-repos/arc-workflows#18]
need to write some tests buuut I think we need to change [this api gateway response pattern](https://github.com/arc-repos/arc-workflows/blob/master/src/create/aws/_create-route/_create-resource/_get-pattern.js#L5) to something like below

```
(.*statusCode\":302.*)|^(http:\/\/|https:\/\/|\/.*)
```

this will allow 

```javascript
var arc = require('@architect/functions')

function route(req, res) {
  res({
    location: 'https://wtfjs.com'
  })
}

exports.handler = arc.html.post(route)
```

The regexp above also allows for statusCode to be invoked with a JSON payload to allow headers other than `Location` be set during `302`.  (Small enhancement I've been intending for a while.) Also: this will all be completely backwards compatible but old API Gateway routes will need to be deleted in the AWS console and recreated by running `npm run create` to get the new functionality.

**Comment by jondavidjohn** [comment]
I seem to be running into an issue when trying this out.

```js
res({
  location: `${FRONTEND_LOGIN_URL}/${user.api_key}`
})
```

```
SyntaxError: Unexpected token h in JSON at position 0
    at JSON.parse ()
    at _local (.../node_modules/@architect/workflows/src/sandbox/http/index.js:86:26)
    at _write (.../node_modules/@architect/functions/src/http/_response.js:16:7)
    at _update (.../node_modules/@architect/functions/src/http/session/write.js:24:5)
    at Response._create (.../node_modules/@architect/functions/src/http/session/_update.js:16:7)
    at Request. (.../node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (.../node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (.../node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (.../node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (.../node_modules/aws-sdk/lib/request.js:22:10)
```

**Comment by brianleroux** [comment]
Arg, ya I have yet to fix this. Only relative redirects possible (not fully absolute urls / x-domain)
