### ISSUE TITLE
[Bug] npm run dns error

### ISSUE THREAD

**Issue by TheLucasMoore** [arc-repos/arc-workflows#29]
I'm trying to use arc `npm run dns` with a domain name I've purchased on AWS.

First it was:
```javascript
/Users/.../node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^
TypeError: Cannot read property 'CertificateArn' of undefined
    at Response.<anonymous> (/.../node_modules/@architect/workflows/src/dns/04-create-domain.js:42:92)
    at Request.<anonymous> (.../node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (.../node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (.../node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (.../node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/.../node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (.../node_modules/aws-sdk/lib/state_machine.js:14:12)
    at .../node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (.../node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (.../node_modules/aws-sdk/lib/request.js:685:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! arc_pizza@1.0.0 dns: `AWS_PROFILE=default AWS_REGION=us-east-1 arc-dns`
npm ERR! Exit status 1
```
There are two emails from AWS for `domain.com` and `*domain.com`. I had missed the second one, so it timed out and caused that error. It might be worth rescuing that error with a more helpful error like "did you validate both certificates?". I'm happy to put in a PR for that.

After validating them both, I now get this error though:
```javascript
...node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

BadRequestException: The domain name you provided already exists.
    at Object.extractError (/.../node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.extractError (/.../node_modules/aws-sdk/lib/protocol/rest_json.js:45:8)
    at Request.callListeners (/.../node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/.../node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/.../node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/.../node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/.../node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /.../node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/.../node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/.../node_modules/aws-sdk/lib/request.js:685:12)
```

**Comment by TheLucasMoore** [comment]
I'm following the [custom dns](https://arc.codes/guides/custom-dns) guide to see if there's a legit problem too.

**Comment by brianleroux** [comment]
Oh! I think I've seen this. Do you have the domain setup in API Gateway already per chance? I think this is the 'custom domains' part of that failing.

**Comment by brianleroux** [comment]
Any update @TheLucasMoore ?

**Comment by brianleroux** [comment]
(closing but pls feel free to re-open if you wanna collab on hunting this down @TheLucasMoore 🙏 )

**Comment by TheLucasMoore** [comment]
Ah, yes. Good call. This turned out to be a Route53 configuration issue on my end.

**Comment by brianleroux** [comment]
Cool np! Lmk if anything else comes up 🍻
