### ISSUE TITLE
deploy doesn't check for empty reply when calling gateway.getRestApis

### ISSUE THREAD

**Issue by morganrallen** [arc-repos/arc-workflows#42]
`_get-url` checks for an error being returned but doesn't check if `result.items` is empty.

https://github.com/arc-repos/arc-workflows/blob/master/src/deploy/src/_get-url.js#L24
As a result line 28 will throw a `TypeError`.

Unsure as of yet how I got here but would think an extra check on `items.length` would be appropriate.

stacktrace:
```
TypeError: Cannot read property 'id' of undefined
    at Response._getRestApis (/tmp/arcs/node_modules/@architect/workflows/src/deploy/src/_get-url.js:30:95)
    at Request.<anonymous> (/tmp/arcs/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/tmp/arcs/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/tmp/arcs/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/tmp/arcs/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/tmp/arcs/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/tmp/arcs/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /tmp/arcs/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/tmp/arcs/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/tmp/arcs/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/tmp/arcs/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/tmp/arcs/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/tmp/arcs/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/tmp/arcs/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/tmp/arcs/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /tmp/arcs/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/tmp/arcs/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/tmp/arcs/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/tmp/arcs/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/tmp/arcs/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/tmp/arcs/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/tmp/arcs/node_modules/aws-sdk/lib/request.js:22:10)
```

**Comment by morganrallen** [comment]
I started over and it worked this time. I think what happened was `create` failed (TooManyRequests) and I hadn't noticed. Then deploy appeared to work but failed when trying to return the URLs. So it appears to have gotten into an in between state and `deploy` isn't checking if it can actually depoy.
