### ISSUE TITLE
Better dynamoDB errors / fixing a `unknown key type`

### ISSUE THREAD

**Issue by jonathanstiansen** [arc-repos/arc-workflows#44]
When attempting to get this table created:

```
@tables
users
  insert Lambda
  update Lambda
  userID *String
  mac String
  email String
  checkinDay **Number
```
I'm getting this error:

```
create @tables worknicer_meraki-production-users
/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

Error: Unknown key type.
    at getKeyType (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/@architect/workflows/src/create/aws/create-tables/_get-key-type.js:25:11)
    at keys.map.k (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/@architect/workflows/src/create/aws/create-tables/_get-key-schema.js:7:16)
    at Array.map (<anonymous>)
    at getKeySchema (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/@architect/workflows/src/create/aws/create-tables/_get-key-schema.js:4:15)
    at Array._createTable (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/@architect/workflows/src/create/aws/create-tables/_create-table.js:36:26)
    at module.exports (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/run-waterfall/index.js:24:13)
    at Response._tables (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/@architect/workflows/src/create/aws/create-tables/_create-table.js:31:9)
    at Request.<anonymous> (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
```

I think I've come close to copy and pasting the table keys from the site, so I think I'm missing something. There was an error that happened before, and I changed the keys to try to fix it - the error looked like this, you'll see below that I was trying to call the table `checked_in` originally:

```
create @tables worknicer_meraki-staging-checked_in
create @tables worknicer_meraki-production-checked_in
{ ValidationException: 1 validation error detected: Value '[com.amazonaws.dynamodb.v20120810.KeySchemaElement@b35673cc, com.amazonaws.dynamodb.v20120810.KeySchemaElement@7b540b48, com.amazonaws.dynamodb.v20120810.KeySchemaElement@1a5e0722]' at 'keySchema' failed to satisfy constraint: Member must have length less than or equal to 2
    at Request.extractError (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: '1 validation error detected: Value \'[com.amazonaws.dynamodb.v20120810.KeySchemaElement@b35673cc, com.amazonaws.dynamodb.v20120810.KeySchemaElement@7b540b48, com.amazonaws.dynamodb.v20120810.KeySchemaElement@1a5e0722]\' at \'keySchema\' failed to satisfy constraint: Member must have length less than or equal to 2',
  code: 'ValidationException',
  time: 2018-01-17T13:47:54.287Z,
  requestId: 'SF5O1MD7KK6HA5G52CHP280SJ7VV4KQNSO5AEMVJF66Q9ASUAAJG',
  statusCode: 400,
  retryable: false,
  retryDelay: 39.0483939613061 }
{ ValidationException: 1 validation error detected: Value '[com.amazonaws.dynamodb.v20120810.KeySchemaElement@64f4fb9, com.amazonaws.dynamodb.v20120810.KeySchemaElement@ce4ce735, com.amazonaws.dynamodb.v20120810.KeySchemaElement@e646f14d]' at 'keySchema' failed to satisfy constraint: Member must have length less than or equal to 2
    at Request.extractError (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: '1 validation error detected: Value \'[com.amazonaws.dynamodb.v20120810.KeySchemaElement@64f4fb9, com.amazonaws.dynamodb.v20120810.KeySchemaElement@ce4ce735, com.amazonaws.dynamodb.v20120810.KeySchemaElement@e646f14d]\' at \'keySchema\' failed to satisfy constraint: Member must have length less than or equal to 2',
  code: 'ValidationException',
  time: 2018-01-17T13:47:54.300Z,
  requestId: '855G8REKA0Q2HB9VQI0PECOH8VVV4KQNSO5AEMVJF66Q9ASUAAJG',
  statusCode: 400,
  retryable: false,
  retryDelay: 23.543534007660426 }
create: /Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/src/tables/checked_in-insert
create: /Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/src/tables/checked_in-update
create: worknicer_meraki-staging-checked_in-insert
create: worknicer_meraki-production-checked_in-update
create: worknicer_meraki-staging-checked_in-update
create: worknicer_meraki-production-checked_in-insert
{ ResourceNotFoundException: Requested resource not found: Table: worknicer_meraki-production-checked_in not found
    at Request.extractError (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'Requested resource not found: Table: worknicer_meraki-production-checked_in not found',
  code: 'ResourceNotFoundException',
  time: 2018-01-17T13:48:01.796Z,
  requestId: 'L0QGQH4ARDLB516P7TCR0RSGTVVV4KQNSO5AEMVJF66Q9ASUAAJG',
  statusCode: 400,
  retryable: false,
  retryDelay: 1.0897362057940008 }
{ ResourceNotFoundException: Requested resource not found: Table: worknicer_meraki-staging-checked_in not found
    at Request.extractError (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'Requested resource not found: Table: worknicer_meraki-staging-checked_in not found',
  code: 'ResourceNotFoundException',
  time: 2018-01-17T13:48:01.820Z,
  requestId: '27IDUD8R6K1QCJMRGBDN3M8R77VV4KQNSO5AEMVJF66Q9ASUAAJG',
  statusCode: 400,
  retryable: false,
  retryDelay: 29.936978811862446 }
{ ResourceNotFoundException: Requested resource not found: Table: worknicer_meraki-staging-checked_in not found
    at Request.extractError (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'Requested resource not found: Table: worknicer_meraki-staging-checked_in not found',
  code: 'ResourceNotFoundException',
  time: 2018-01-17T13:48:01.882Z,
  requestId: 'LJM3BHJIM1FBNV0OCBHGB3CMEFVV4KQNSO5AEMVJF66Q9ASUAAJG',
  statusCode: 400,
  retryable: false,
  retryDelay: 28.071081759955007 }
{ ResourceNotFoundException: Requested resource not found: Table: worknicer_meraki-production-checked_in not found
    at Request.extractError (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.callListeners (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/jono/Dropbox/philia_contracts/worknicer/meraki_cobot_auth/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
  message: 'Requested resource not found: Table: worknicer_meraki-production-checked_in not found',
  code: 'ResourceNotFoundException',
  time: 2018-01-17T13:48:01.921Z,
  requestId: 'IFP35T0GTF0GH88SPN32OAABVFVV4KQNSO5AEMVJF66Q9ASUAAJG',
  statusCode: 400,
  retryable: false,
  retryDelay: 22.230181271430062 }
```

I'm running:
```
$ node -v                                                                                                                                                                  
v8.7.0
$ npm -v                                                                                                                                                                    
5.5.1
```

**Comment by jonathanstiansen** [comment]
The issue was that you cannot do `String` You must do `*String` or `**String`. Having an error that describes that, or even propagates the incorrect key would be useful.

**Comment by jonathanstiansen** [comment]
Another note in case any newb sees this and has the same problem. I was trying to use dynamo as a normal SQL db. It's not. It's schemaless (kindof), which means it only allows one partition key signified with a `*` and one *optional* sorting key, signified with a `**`. That's it, both of those together form one key, and that's all you get. If you need more info, start [here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStarted.NodeJs.html).

**Comment by brianleroux** [comment]
Great feedback thx @jonathanstiansen ! (Will look at getting this error handling a bit more clear / don't hesitate to (join our slack)[https://join.slack.com/t/architecture-as-text/shared_invite/MjE2MzU4Nzg0NTY1LTE1MDA2NzgyMzYtODE2NzRkOGRmYw] and ping me in real time if you have questions!
