### ISSUE TITLE
from `npm run dns` - if certs not issued, throws request error

### ISSUE THREAD

**Issue by remy** [arc-repos/arc-workflows#49]
This line: https://github.com/arc-repos/arc-workflows/blob/master/src/dns/04-create-domain.js#L41 will throw an exception if the domain hasn't finished issuing the SSL certificates. In my case, the prod domain had been issued, but the `*.domain.com` had not, so this was throwing inside of arc:

```
❯ npm run dns

> domain@1.0.0 dns
> AWS_PROFILE=arc AWS_REGION=us-east-1 arc-dns


Found Route53 hosted zone domain.io

Please ensure your domain registration is using these nameeservers:
ns-1119.awsdns-11.org.
ns-23.awsdns-02.com.
ns-1940.awsdns-50.co.uk.
ns-875.awsdns-45.net.


/Users/remy/Sites/domain/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

TypeError: Cannot read property 'CertificateArn' of undefined
    at Response.<anonymous> (/Users/remy/Sites/domain/node_modules/@architect/workflows/src/dns/04-create-domain.js:41:96)
    at Request.<anonymous> (/Users/remy/Sites/domain/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/Users/remy/Sites/domain/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/remy/Sites/domain/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/remy/Sites/domain/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/remy/Sites/domain/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/remy/Sites/domain/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/remy/Sites/domain/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/remy/Sites/domain/node_modules/aws-sdk/lib/request.js:38:9)
```

**Comment by brianleroux** [comment]
ah, interesting, wonder if the right fix here is to check for issued like this:

https://github.com/arc-repos/arc-workflows/blob/master/src/dns/04-create-domain.js#L34

but in step 2 here:

https://github.com/arc-repos/arc-workflows/blob/master/src/dns/02-ensure-certs.js#L8-L12

so as to ensure its in the state we want…moreso than checking for a state we don't want

(thots here most welcome / this is a newer part of the code so its def not super hardened)
