### ISSUE TITLE
`npm run create` failing on 2.10.16

### ISSUE THREAD

**Issue by mrb** [arc-repos/arc-workflows#72]
**Describe the bug**
npm run create blows up on fresh install

**To Reproduce**
run `npm run create` on a minimal .arc file after following installation instructions

**Expected behavior**
Code to be generated

**Screenshots**
```
  cp(path.join(process.cwd(), '.arc'), path.join(pathToLocalArcCopy, '.arc'))
       ^

TypeError: cp is not a function
    at ChildProcess.win (/Users/mrb/Projects/brainjams/node_modules/@architect/workflows/src/create/aws/_install-workflows-and-data.js:15:8)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
```

**Desktop (please complete the following information):**
OSX 10.12.2

**Comment by brianleroux** [comment]
oh! are you running Node 8.10 or higher? Recently started a refactor to remove 3rd party cp to favor the built in Node one but its new

**Comment by mrb** [comment]
@brianleroux Yep, had 7.9 locally. Will upgrade!

**Comment by mrb** [comment]
@brianleroux Worked on upgrade.
